version: "3.9"
services:
  web:
    image: "cinephila-api"
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1444:1433"
    environment:
      MSSQL_SA_PASSWORD: "ZEmLRGq2_wI_R84S"
      ACCEPT_EULA: "Y"