version: "3.9"
services:
  api:
    image: "cinephila-api"
    build: .
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  cache:
      image: redis:latest
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports: 
      - "1444:1433"
    environment:
      MSSQL_SA_PASSWORD: "ZEmLRGq2_wI_R84S"
      ACCEPT_EULA: "Y"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:-ZEmLRGq2_wI_R84S} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s