# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Cinephila

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cinephila.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8ef9fdfe9b9e497eb3065c080b84eaf8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_067e88dba3f84933988ff40696036cb5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cinephila.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8ef9fdfe9b9e497eb3065c080b84eaf8 }}/webapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Cinephila'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_84ad64c5798c46bda93386dd23e20df5 }}
        images: 'cinephila.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8ef9fdfe9b9e497eb3065c080b84eaf8 }}/webapi:${{ github.sha }}'